baseURL = "https://kathleenou.github.io/personal_website/"
languageCode = "en-us"
title = "Kathleen Ulanday"
theme = "PaperMod"
disableKinds = ["RSS"]

[author]
  name = "Kathleen Ulanday"
  
[[menu.main]]
  name = "Resume"
  url = "https://kathleenou.github.io/personal_website/KathleenUlanday_Resume.pdf"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "/posts/"
  weight = 3